apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.mqtt.persistence.size | quote }}
