{{- if .Values.zigbee2mqtt.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.zigbee2mqtt.ingress.whitelistSourceRange | quote }}
    cert-manager.io/cluster-issuer: {{ .Values.zigbee2mqtt.ingress.certIssuer | quote }}
    {{- if .Values.zigbee2mqtt.ingress.auth.enabled }}
    nginx.ingress.kubernetes.io/auth-url: {{ .Values.zigbee2mqtt.ingress.auth.url | quote }}
    nginx.ingress.kubernetes.io/auth-signin: {{ .Values.zigbee2mqtt.ingress.auth.signin | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.zigbee2mqtt.ingress.className | quote }}
  tls:
    - hosts:
        - {{ .Values.zigbee2mqtt.ingress.host | quote }}
      secretName: {{ .Values.zigbee2mqtt.ingress.tlsSecretName | quote }}
  rules:
    - host: {{ .Values.zigbee2mqtt.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.zigbee2mqtt.service.name }}
                port:
                  number: {{ .Values.zigbee2mqtt.service.port }}
{{- end }}
