ipam:
  mode: kubernetes

kubeProxyReplacement: true

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

# Point Cilium directly at the API server (common on Talos / no kube-proxy)
k8sServiceHost: localhost
k8sServicePort: 7445

# k8sServiceHost: 192.168.3.100
# k8sServicePort: 6443

hubble:
  ui:
    enabled: true
    ingress:
      enabled: true
      className: nginx
      hosts:
        - hubble.homelab.niekvlam.nl
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
      tls:
        - hosts:
            - hubble.homelab.niekvlam.nl
          secretName: hubble-tls
  relay:
    enabled: true

ipv4:
  enabled: true

ipv6:
  enabled: true

# Usually needed so pods can reach the IPv6 internet (egress)
enableIPv6Masquerade: true
# (Optional, usually already on)
enableIPv4Masquerade: true
