apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-secret
  namespace: security
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.vault.clusterStoreName }}
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-secret
    template:
      type: Opaque
      data:
        admin-password: "{{ `{{ .admin }}` }}"
  dataFrom:
    - extract:
        key: {{ .Values.vault.paths.bootstrap | quote }}

