{{- if .Values.features.grafana }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-grafana
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.vault.clusterStoreName }}
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-secret
    template:
      type: Opaque
      data:
        client-id: "{{ `{{ .client_id }}` }}"
        client-secret: "{{ `{{ .client_secret }}` }}"
  dataFrom:
    - extract:
        key: {{ .Values.vault.paths.clients.grafana | quote }}
{{- end }}
---
{{- if .Values.features.argocd }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-argocd
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.vault.clusterStoreName }}
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        oidc.keycloak.clientID: "{{ `{{ .client_id }}` }}"
        oidc.keycloak.clientSecret: "{{ `{{ .client_secret }}` }}"
  dataFrom:
    - extract:
        key: {{ .Values.vault.paths.clients.argocd | quote }}
{{- end }}
---
{{- if .Values.features.homeassistant }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-oauth2-proxy-homeassistant
  namespace: {{ .Values.oauth2Proxy.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.vault.clusterStoreName }}
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-keycloak
    template:
      type: Opaque
      data:
        client-id: "{{ `{{ .client_id }}` }}"
        client-secret: "{{ `{{ .client_secret }}` }}"
        {{ .Values.oauth2Proxy.cookieSecretKey }}: "{{ `{{ .cookie_secret }}` }}"
  dataFrom:
    - extract:
        key: {{ .Values.vault.paths.clients.homeassistant | quote }}
{{- end }}

