apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  # The Longhorn controller/CRDs are wave 0 in the same Application.
  argocd.argoproj.io/sync-wave: "1"
resources:
  - networkpolicy.yaml
  - prometheus-rule.yaml
  - recurring-job.yaml
  - service-monitor.yaml
