apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-shared
  namespace: media
spec:
  accessModes: [ReadWriteMany]
  storageClassName: media-nfs
  resources:
    requests:
      storage: 1Ti

