apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  namespace: media
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector: { matchLabels: { app: seerr } }
  template:
    metadata: { labels: { app: seerr } }
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: seerr
          image: ghcr.io/seerr-team/seerr:v3.3.0
          ports:
            - { name: http, containerPort: 5055 }
          env:
            - { name: LOG_LEVEL, value: "info" }
            - { name: PORT, value: "5055" }
            - { name: TZ, value: "Europe/Amsterdam" }
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          volumeMounts:
            - { name: config, mountPath: /app/config }
          readinessProbe:
            httpGet: { path: /api/v1/settings/public, port: http }
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
          livenessProbe:
            httpGet: { path: /api/v1/settings/public, port: http }
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 3
      volumes:
        - {
            name: config,
            persistentVolumeClaim: { claimName: overseerr-config },
          }
---
apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: media
spec:
  selector: { app: seerr }
  ports:
    - { name: http, port: 5055, targetPort: http }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seerr
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["overseerr.homelab.niekvlam.nl"]
      secretName: overseerr-tls
  rules:
    - host: overseerr.homelab.niekvlam.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: seerr, port: { number: 5055 } }
