apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: obsidian-livesync
  namespace: obsidian-livesync
  labels:
    app.kubernetes.io/name: obsidian-livesync
    app.kubernetes.io/part-of: obsidian-livesync
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: obsidian-livesync
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 5984
