apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-livesync-data
  namespace: obsidian-livesync
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: obsidian-livesync
    app.kubernetes.io/part-of: obsidian-livesync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
