apiVersion: v1
kind: Service
metadata:
  name: pocket-id
  namespace: auth
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: pocket-id
    app.kubernetes.io/part-of: auth
spec:
  selector:
    app.kubernetes.io/name: pocket-id
  ports:
    - name: http
      port: 1411
      targetPort: http
    - name: metrics
      port: 9464
      targetPort: metrics
