apiVersion: v1
kind: Namespace
metadata:
  name: pi5-fan-control
  labels:
    app.kubernetes.io/name: pi5-fan-control
    app.kubernetes.io/part-of: infrastructure
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
