apiVersion: v1alpha1
kind: UserVolumeConfig
name: longhorn
provisioning:
  diskSelector:
    # Place Longhorn data on the non-system NVMe disk.
    match: disk.transport == "nvme" && !system_disk
  minSize: 250GiB
filesystem:
  type: xfs
