# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
{{- if .Values.monitoring.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-grafana
  labels:
    cluster: {{ .Values.cluster.name | quote }}
    app: grafana
  namespace: {{ .Values.cluster.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    app.kubernetes.io/part-of: monitoring
    {{- if .Values.notifications }}
    {{ toYaml .Values.notifications | indent 4 }}
    {{- end }}
spec:
  project: {{ .Values.cluster.name }}
  destination:
    server: {{ .Values.cluster.url | default "https://kubernetes.default.svc" | quote }}
    namespace: monitoring
  syncPolicy:
    {{- if .Values.sync }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: {{ .Values.monitoring.grafana.version | quote }}
    helm:
      releaseName: grafana
      values: |
        ingress:
{{ toYaml .Values.monitoring.grafana.ingress | indent 10 }}
        datasources:
{{ toYaml .Values.monitoring.grafana.datasources | indent 10 }}
{{- end }}

