# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
{{- if .Values.monitoring.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-promtail
  labels:
    cluster: {{ .Values.cluster.name | quote }}
    app: promtail
  namespace: {{ .Values.cluster.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    app.kubernetes.io/part-of: monitoring
    {{- if .Values.notifications }}
    {{ toYaml .Values.notifications | indent 4 }}
    {{- end }}
spec:
  project: {{ .Values.cluster.name }}
  destination:
    server: {{ .Values.cluster.url | default "https://kubernetes.default.svc" | quote }}
    namespace: monitoring
  syncPolicy:
    {{- if .Values.sync }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/audit: privileged
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: {{ .Values.monitoring.promtail.version | default "6.15.5" | quote }}
    helm:
      releaseName: promtail
      values: |
        config:
{{ toYaml .Values.monitoring.promtail | indent 10 }}
{{- end }}

