apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin-password
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      data:
        admin.password: "{{ .admin_bcrypt }}"
        admin.passwordMtime: "{{ .mtime }}"
  data:
    - secretKey: admin_bcrypt
      remoteRef:
        key: kv/k8s/argocd/admin
        property: passwordBcrypt
    - secretKey: mtime
      remoteRef:
        key: kv/k8s/argocd/admin
        property: passwordMtime
