# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
{{ if .Values.certmanager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-cert-manager-custom
  labels:
    cluster: {{ .Values.cluster.name | quote }}
    app: cert-manager
  namespace: {{ .Values.cluster.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    app.kubernetes.io/part-of: cert-manager
    {{- if .Values.notifications }}
    {{ toYaml .Values.notifications | indent 4 }}
    {{- end }}
spec:
  project: {{ .Values.cluster.name }}
  destination:
    server: {{ .Values.cluster.url | default "https://kubernetes.default.svc" | quote }}
    namespace: cert-manager
  syncPolicy:
    {{- if .Values.sync }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
  source:
    repoURL: git@github.com:Alphaegen/talos-homelab.git
    path: gitops/infra-custom/cert-manager
    targetRevision: HEAD
    helm:
      version: v3
      releaseName: cert-manager-custom
      values: |
          email: {{ .Values.certmanager.acme.email }}
          server: {{ .Values.certmanager.acme.server }}
{{ end }}
