{{- if .Values.stores.vault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.stores.vault.auth.serviceAccount.name }}
  namespace: {{ .Values.stores.vault.auth.serviceAccount.namespace }}
{{- end }}
