{{- if .Values.stores.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.stores.vault.name }}
spec:
  provider:
    vault:
      server: {{ .Values.stores.vault.server | quote }}
      path: {{ .Values.stores.vault.path | quote }}
      version: {{ .Values.stores.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.stores.vault.auth.mountPath | quote }}
          role: {{ .Values.stores.vault.auth.role | quote }}
          serviceAccountRef:
            name: {{ .Values.stores.vault.auth.serviceAccount.name }}
            namespace: {{ .Values.stores.vault.auth.serviceAccount.namespace }}
{{- end }}
