{{- if .Values.stores.onepassword.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.stores.onepassword.name }}
spec:
  provider:
    onepasswordSDK:
      vault: {{ required "stores.onepassword.vault is required when stores.onepassword.enabled=true" .Values.stores.onepassword.vault | quote }}
      auth:
        serviceAccountSecretRef:
          name: {{ .Values.stores.onepassword.auth.serviceAccountSecretRef.name }}
          key: {{ .Values.stores.onepassword.auth.serviceAccountSecretRef.key }}
          namespace: {{ .Values.stores.onepassword.auth.serviceAccountSecretRef.namespace }}
      {{- if .Values.stores.onepassword.integrationInfo.enabled }}
      integrationInfo:
        name: {{ .Values.stores.onepassword.integrationInfo.name | quote }}
        version: {{ .Values.stores.onepassword.integrationInfo.version | quote }}
      {{- end }}
      {{- if .Values.stores.onepassword.cache.enabled }}
      cache:
        ttl: {{ .Values.stores.onepassword.cache.ttl | quote }}
        maxSize: {{ .Values.stores.onepassword.cache.maxSize }}
      {{- end }}
{{- end }}
