{{- with .Values.integrations.tailscale }}
{{- if .enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .operatorOAuthSecret.name }}
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: {{ .operatorOAuthSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .secretStoreRef.kind | quote }}
    name: {{ .secretStoreRef.name | quote }}
  target:
    name: {{ .operatorOAuthSecret.name }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .operatorOAuthSecret.remoteRef.clientIdKey | quote }}
        {{- if .operatorOAuthSecret.remoteRef.clientIdProperty }}
        property: {{ .operatorOAuthSecret.remoteRef.clientIdProperty | quote }}
        {{- end }}
    - secretKey: client_secret
      remoteRef:
        key: {{ .operatorOAuthSecret.remoteRef.clientSecretKey | quote }}
        {{- if .operatorOAuthSecret.remoteRef.clientSecretProperty }}
        property: {{ .operatorOAuthSecret.remoteRef.clientSecretProperty | quote }}
        {{- end }}
{{- end }}
{{- end }}
