{{- if .Values.security.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-external-secrets
  labels:
    cluster: {{ .Values.cluster.name | quote }}
    app: external-secrets
  namespace: {{ .Values.cluster.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: {{ .Values.cluster.name }}
  destination:
    server: {{ .Values.cluster.url | default "https://kubernetes.default.svc" | quote }}
    namespace: external-secrets
  syncPolicy:
    {{- if .Values.sync }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: {{ .Values.security.eso.version | quote }}
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        serviceMonitor:
          enabled: true
          labels:
            release: {{ .Values.security.eso.serviceMonitorLabel }}
        webhook:
          # keeps it simple; you can enable later for stricter admission
          create: true
        certController:
          create: true
{{- end }}

