{{- if .Values.operatorOAuthSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.operatorOAuthSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.operatorOAuthSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.secretStoreRef.kind | quote }}
    name: {{ .Values.secretStoreRef.name | quote }}
  target:
    name: {{ .Values.operatorOAuthSecret.name }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .Values.operatorOAuthSecret.remoteRef.clientIdKey | quote }}
        {{- if .Values.operatorOAuthSecret.remoteRef.clientIdProperty }}
        property: {{ .Values.operatorOAuthSecret.remoteRef.clientIdProperty | quote }}
        {{- end }}
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.operatorOAuthSecret.remoteRef.clientSecretKey | quote }}
        {{- if .Values.operatorOAuthSecret.remoteRef.clientSecretProperty }}
        property: {{ .Values.operatorOAuthSecret.remoteRef.clientSecretProperty | quote }}
        {{- end }}
{{- end }}
