cluster:
  name: homelab.niekvlam
  namespace: argocd

sync: true

ingressController:
  enabled: true
  class: nginx
  version: 4.13.0

metallb:
  enabled: true
  version: 0.15.2
  endpoints:
    - "192.168.3.110-192.168.3.129"

longhorn:
  enabled: true
  version: 1.9.1

certmanager:
  enabled: true
  version: v1.18.2
  acme:
    email: vlam4695+homelab@gmail.com
    server: "https://acme-v02.api.letsencrypt.org/directory"

sealedsecrets:
  enabled: true
  version: 2.17.3

ceph:
  enabled: true
  version: 1.17.7

monitoring:
  enabled: true
  grafana:
    version: 9.3.1
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt-dns
      hosts: [ "grafana.homelab.niekvlam.nl" ]
      tls:
        - secretName: grafana-tls
          hosts: [ "grafana.homelab.niekvlam.nl" ]
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://loki-gateway.monitoring.svc:80
    dashboards:
      default:
        node-exporter:
          gnetId: 1860
          revision: 32
          datasource: Prometheus
        coredns:
          gnetId: 14981
          revision: 2
          datasource: Prometheus
        loki-overview:
          gnetId: 14055
          revision: 6
          datasource: Loki
        k8s:
          gnetId: 15661
          revision: 2
          datasource: Prometheus
        argocd:
          gnetId: 14584
          revision: 1
        cert-manager:
          gnetId: 11001
          revision: 1

  loki:
    version: 6.35.1
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 20Gi
        storageClassName: longhorn
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false


    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: filesystem
    limits_config:
      retention_period: 168h  # 7d
      allow_structured_metadata: false
    schemaConfig:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    gateway:
      enabled: true


  promtail:
    version: 6.17.0
    extraVolumes:
      - name: positions
        hostPath:
          path: /var/lib/promtail
          type: DirectoryOrCreate
    extraVolumeMounts:
      - name: positions
        mountPath: /run/promtail
        readOnly: false
    config:
      positions:
        filename: /run/promtail/positions.yaml
      clients:
        - url: http://loki-gateway.monitoring.svc:80/loki/api/v1/push
      snippets:
        pipelineStages:
          - cri: {}

  prometheus:
    version: 76.1.0
    prometheusSpec:
      retention: 30d
      retentionSize: 20GiB
      walCompression: true
      scrapeInterval: 30s
      enableAdminAPI: false

  alertmanager:
    enabled: true

  kubeStateMetrics:
    enabled: true
  nodeExporter:
    enabled: true

raw:
  version: 2.0.0
