namespace: tailscale

connector:
  enabled: true
  name: home-lan
  hostnamePrefix: home-lan
  replicas: 1
  tags:
    - tag:home-lan-router
  subnetRouter:
    advertiseRoutes:
      - 192.168.3.0/24
  exitNode:
    enabled: true

secretStoreRef:
  kind: ClusterSecretStore
  name: onepassword

operatorOAuthSecret:
  enabled: true
  name: operator-oauth
  refreshInterval: 1h
  remoteRef:
    clientIdKey: tailscale-operator/client_id
    clientSecretKey: tailscale-operator/client_secret
    clientIdProperty: ""
    clientSecretProperty: ""
