stores:
  onepassword:
    enabled: true
    name: onepassword
    vault: "Homelab"
    auth:
      serviceAccountSecretRef:
        name: onepassword-service-account-token
        key: token
        namespace: external-secrets
    integrationInfo:
      enabled: true
      name: external-secrets
      version: v1
    cache:
      enabled: false
      ttl: 5m
      maxSize: 100

integrations:
  certManager:
    enabled: true

  tailscale:
    enabled: true
    namespace: tailscale
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    operatorOAuthSecret:
      name: operator-oauth
      refreshInterval: 24h
      remoteRef:
        clientIdKey: tailscale-operator/client_id
        clientSecretKey: tailscale-operator/client_secret
        clientIdProperty: ""
        clientSecretProperty: ""
