stores:
  vault:
    enabled: false
    name: vault
    server: http://vault-active.security.svc:8200
    path: kv
    version: v2
    auth:
      mountPath: kubernetes
      role: eso
      serviceAccount:
        name: eso-vault
        namespace: external-secrets

  onepassword:
    enabled: true
    name: onepassword
    vault: "Homelab"
    auth:
      serviceAccountSecretRef:
        name: onepassword-service-account-token
        key: token
        namespace: external-secrets
    integrationInfo:
      enabled: true
      name: external-secrets
      version: v1
    cache:
      enabled: false
      ttl: 5m
      maxSize: 100

argocd:
  repoCredentials:
    enabled: true
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    sshPrivateKeyRemoteRef:
      # 1Password path format: <item>/<field>
      key: argocd-repo/sshPrivateKey
      property: ""
    repos:
      - secretName: repo-1798823262
        namespace: argocd
        repositoryName: homelab-repo
        project: default
        url: git@github.com:Alphaegen/talos-homelab.git
        type: git
      - secretName: repo-1485164468
        namespace: argocd
        project: homelab.niekvlam
        url: git@github.com:Alphaegen/talos-homelab.git
        type: git
