{{- range .Values.ipAddressPools }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Values.namespace | default "metallb-system" | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
  {{- range .addresses }}
    - {{ . | quote }}
  {{- end }}
{{- end }}
