apiVersion: v1
kind: Namespace
metadata:
  name: etcd-backup
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: etcd-backup
    app.kubernetes.io/part-of: homelab
