apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup-snapshots
  namespace: etcd-backup
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: etcd-backup
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteMany
  volumeName: etcd-backup-snapshots
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
