apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-notifications
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-notifications
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          managed-by: external-secrets
  data:
    - secretKey: NTFY_URL
      remoteRef:
        key: alertmanager/NTFY_URL
    - secretKey: NTFY_TOKEN
      remoteRef:
        key: alertmanager/NTFY_TOKEN
