# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
{{- if .Values.media.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-media
  namespace: {{ .Values.cluster.namespace | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    cluster: {{ .Values.cluster.name | quote }}
    app: media
  annotations:
    # after provisioner is up
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: {{ .Values.cluster.name }}
  destination:
    server: {{ .Values.cluster.url | default "https://kubernetes.default.svc" | quote }}
    namespace: media
  syncPolicy:
    {{- if .Values.sync }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: {{ .Values.cluster.repoURL | quote }}
    targetRevision: {{ .Values.cluster.revision | default "main" | quote }}
    path: gitops/infra-custom/media
{{- end }}

