# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
{{- if .Values.metallb.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "infra.appName" (dict "root" . "name" "metallb") }}
  labels:
    cluster: {{ .Values.cluster.name | quote }}
    app: metallb
  namespace: {{ .Values.cluster.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    app.kubernetes.io/part-of: metallb
    {{- if .Values.notifications }}
    {{ toYaml .Values.notifications | nindent 4 }}
    {{- end }}
spec:
  project: {{ include "infra.projectName" . }}
  destination:
    server: {{ .Values.cluster.url | default "https://kubernetes.default.svc" | quote }}
    namespace: metallb-system
  syncPolicy:
    {{- if .Values.sync }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: {{ .Values.metallb.version | quote }}
    helm:
      version: v3
      releaseName: metallb
      values: |
        prometheus:
          serviceMonitor:
            enabled: false
        frr-k8s:
          prometheus:
            serviceMonitor:
              enabled: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "infra.appName" (dict "root" . "name" "metallb-config") }}
  labels:
    cluster: {{ .Values.cluster.name | quote }}
    app: metallb-config
  namespace: {{ .Values.cluster.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    app.kubernetes.io/part-of: metallb
    {{- if .Values.notifications }}
    {{ toYaml .Values.notifications | indent 4 }}
    {{- end }}
spec:
  project: {{ include "infra.projectName" . }}
  destination:
    server: {{ .Values.cluster.url | default "https://kubernetes.default.svc" | quote }}
    namespace: metallb-system
  syncPolicy:
    {{- if .Values.sync }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: {{ .Values.cluster.repoURL | quote }}
    path: gitops/infra-custom/metallb
    targetRevision: {{ .Values.cluster.revision | default "main" | quote }}
    helm:
      releaseName: metallb-config
      values: |
        namespace: metallb-system
        ipAddressPool:
          name: public
          addresses:
          {{- range .Values.metallb.endpoints }}
            - {{ . }}
          {{- end }}
        l2Advertisement:
          name: public
          enabled: true
{{- end }}
