apiVersion: v1
kind: ConfigMap
metadata:
  name: bookorbit-postgres-initdb
  namespace: bookorbit
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  01-extensions.sql: |
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE EXTENSION IF NOT EXISTS vector;
