apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dumbpad-data
  namespace: dumbpad
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: dumbpad
    app.kubernetes.io/part-of: dumbpad
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
