global:
  domain: argocd.homelab.niekvlam.nl

configs:
  params:
    server.insecure: true

server:
  replicas: 2
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

redis-ha:
  enabled: true

controller:
  replicas: 1

repoServer:
  replicas: 2

applicationSet:
  replicas: 2
