global:
  domain: argocd.homelab.niekvlam.nl

redis-ha:
  enabled: true

configs:
  params:
    server.insecure: true

server:
  replicas: 2
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: "letsencrypt-dns"
    extraTls:
      - hosts: [ "argocd.homelab.niekvlam.nl" ]
        secretName: argocd-tls
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      interval: 30s
      additionalLabels:
        release: kube-prometheus-stack

controller:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      interval: 30s
      additionalLabels:
        release: kube-prometheus-stack

repoServer:
  replicas: 2
  nodeSelector:
    kubernetes.io/os: linux
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - rpi-w-2
                  - rpi-w-3
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      interval: 30s
      additionalLabels:
        release: kube-prometheus-stack

applicationSet:
  replicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      interval: 30s
      additionalLabels:
        release: kube-prometheus-stack

notifications:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      interval: 30s
      additionalLabels:
        release: kube-prometheus-stack
