apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: baseline-security
spec:
  validationFailureAction: {{- if eq .Values.mode "enforce" -}}Enforce{{- else -}}Audit{{- end }}
  background: true
  rules:
    - name: disallow-latest
      match:
        any:
          - resources:
              kinds: ["Pod","Deployment","StatefulSet","DaemonSet","Job","CronJob"]
              namespaces:
                - "!kube-system"
                {{- range .Values.excludeNamespaces }}
                - "!{{ . }}"
                {{- end }}
      validate:
        message: "Images must not use the :latest tag"
        pattern:
          spec:
            containers:
              - image: "!*:latest"

    - name: require-probes
      match:
        any:
          - resources:
              kinds: ["Deployment","StatefulSet"]
              namespaces:
                - "!kube-system"
                {{- range .Values.excludeNamespaces }}
                - "!{{ . }}"
                {{- end }}
      validate:
        message: "Containers must define liveness and readiness probes"
        pattern:
          spec:
            template:
              spec:
                containers:
                  - livenessProbe: { exists: true }
                    readinessProbe: { exists: true }

    - name: restrict-privileges
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces:
                - "!kube-system"
                {{- range .Values.excludeNamespaces }}
                - "!{{ . }}"
                {{- end }}
      validate:
        message: "Privileged/host features are restricted by default"
        pattern:
          spec:
            hostNetwork: false
            hostPID: false
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
            securityContext:
              runAsNonRoot: true

